### PR TITLE
Implement Openstreetmap provider

### PR DESCRIPTION
**Pull request by pjsier**
Thanks for putting this library together! I took a stab at implementing an OpenStreetMap provider here since it was listed in #1 

I tried to follow the patterns from the OpenCage provider and used the builder pattern for specifying additional parameters, but I'm new to Rust so let me know if anything seems off. I'd like to use the `InputBounds` struct for the `viewport` parameter here, but wanted to check and see what the best way of restructuring that would be

### CODE REVIEW

**Comment by mthh** [comment]
I am not (yet !) contributor to [georust/geocoding](https://github.com/georust/geocoding) but I was wondering : shouldn't it be possible, for the user, to specify the endpoint address when creating a new `Openstreetmap` struct?
(since it is possible to install a local instance of Nominatim, as described on http://nominatim.org/release-docs/latest/admin/Installation/)

In fact it looks already feasible with your PR, but it will requires some boilerplate (compared to having a `with_endpoint` constructor for example).

**Comment by urschrei** [comment]
If you'd like to use the `InputBounds` struct, you'll have to either move it into `lib.rs` and make it `pub`, then re-import into `opencage`, or create a separate `util` module or similar and import it from there. I'd go with the former for now. Also, it looks like you'll have to do some of the arithmetic yourself for the `OpenStreetMap` bounds, since the call requires four coordinates,  but `InputBounds` only specifies top left and bottom right – if you want to impl an additional method on `InputBounds` that does the arithmetic and returns an array, go for it!

**Comment by pjsier** [comment]
Thanks for clarifying! I implemented moving `InputBounds` into `lib.rs` here. It looks like the `viewbox` parameter in Nominatim takes the same input format as OpenCage, and it seems to be working now.

I'd also be interested in adding the ability to specify a custom endpoint, is a separate constructor the most straightforward way of doing that?

**Comment by urschrei** [comment]
>I'd also be interested in adding the ability to specify a custom endpoint, is a separate constructor the most straightforward way of doing that?

Yep I'd just add a `new_with_endpoint` or similar impl. Up to you whether you'd like to perform any kind of validation using e.g. `rust-url` to ensure it's a valid URL.

**Comment by pjsier** [comment]
Great, thanks! Just made that update so this should be ready for review

**Comment by urschrei** [comment]
bors retry

**Comment by urschrei** [comment]
Looks good to me!

**Pull request merged**
