### PR TITLE
add GeoAdmin provider

### PR DESCRIPTION
**Pull request by b4l**
This adds the GeoAdmin provider for geocoding in Switzerland. It's my first contribution to anything - so feedback is welcome.

### CODE REVIEW

**Comment by urschrei** [comment]
Hi, thanks for the PR! I note that you're proposing both an API change, and a new provider. Please split this PR so we can review and discuss the merits of the API change separately (fwiw, I don't think returning a `Result<Option>` is necessarily a problem or something we're opposed to)

**Comment by frewsxcv** [comment]
sorry for not reviewing this sooner! your changes looked good to me, if you reopen i can merge it for you 👋

**Comment by b4l** [comment]
@frewsxcv no problem! working on this i realised that regional geocoding providers probably need some further attention. the main unresolved issues i encountered are local coordinate systems. how should this be addressed?

**Comment by urschrei** [comment]
@b4l Can you say a little more about how the local coordinates are used? Either way, we can enable conversion between EPSG4326 and local coordinate systems using https://github.com/georust/proj, although that requires the user to have a recent  (6.0.0) `PROJ` installation on their system.

**Comment by b4l** [comment]
@urschrei The geoadmin provider uses EPSG:2056 or its predecessor internally. Reverse geocoding requests only accept these CRS.  The responses have additionally WGS84 coordinate as well.
Providing a convenient and consistent WGS84 interface comes with the dependency tradeoff in this case. I am not sure how i fell about this.

**Comment by urschrei** [comment]
Ahh, OK. You could implement it without conversion, and document the requirement for EPSG:2065 coordinates when reverse-geocoding, along with a bounding-box check (it's not perfect, but it's cheap and not a bad trade-off), or we could go with `proj`, putting the `GeoAdmin` provider behind a feature flag.

**Comment by b4l** [comment]
Yes, both ok. Maybe the first solution is to prefer at the moment for maintainability and let the users do conversion if needed.

**Comment by urschrei** [comment]
👍

**Pull request merged**
