### PR TITLE
Provide rustls feature

### PR DESCRIPTION
**Pull request by flosse**
In some environments openssl is not available so with `rustls-tls` we can solve that problem.

### CODE REVIEW

**Comment by urschrei** [comment]
Looks good to me, thanks for adding this! Could you add some docs about the new feature availability to `lib.rs`?

**Comment by flosse** [comment]
done!

**Comment by seanpianka** [comment]
Any update on getting this merged into master?

**Comment by urschrei** [comment]
Whoops, sorry about the delay.

**Comment by flosse** [comment]
@urschrei the build fails but that's also the case with the current master (9b33934ed521c5cb352411a5a4035a9896662eb1)

**Comment by urschrei** [comment]
Yeah the tests are…not optimal because the results change often.

**Comment by flosse** [comment]
@urschrei Would you mind to publish a new version to crates.io?

**Comment by frewsxcv** [comment]
👋 i can do this now

**Comment by frewsxcv** [comment]
done! published 0.3.1

**Pull request merged**
